# Generated by Django 3.0.5 on 2020-04-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='user',
        ),
        migrations.AddField(
            model_name='friends',
            name='user1',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='friends',
            name='user2',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
