# Generated by Django 3.0.2 on 2020-02-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20200227_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='condition',
            field=models.CharField(choices=[('GD', 'Good'), ('AVG', 'Average'), ('BD', 'Bad')], default='AVG', max_length=3),
        ),
    ]
