# Generated by Django 3.0.2 on 2020-02-28 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_itemlist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
