# Generated by Django 3.0.4 on 2020-03-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='curr_user',
            field=models.TextField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
