# Generated by Django 3.0.2 on 2020-04-02 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=20)),
                ('image', models.ImageField(default='photos/default.jpg', upload_to='photos')),
                ('likes', models.IntegerField(default=0)),
                ('likelist', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objid', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
