# Generated by Django 3.0.2 on 2020-04-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20200402_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpost',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
