# Generated by Django 3.0.2 on 2020-04-02 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20200401_1453'),
        ('blogpost', '0004_auto_20200402_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpost',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.GroupTable'),
        ),
    ]
