# Generated by Django 3.0.2 on 2020-03-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='user',
        ),
    ]
