# Generated by Django 3.0.2 on 2020-04-01 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0007_invitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupusertable',
            unique_together={('group', 'user')},
        ),
    ]
