# Generated by Django 3.0.2 on 2020-03-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200305_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='bg',
            field=models.ImageField(default='background/default.jpg', upload_to='background'),
        ),
    ]
