# Generated by Django 3.0.2 on 2020-03-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptable',
            name='desc',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='grouptable',
            name='image',
            field=models.ImageField(default='background/default.jpg', upload_to='group_pics'),
        ),
    ]
