# Generated by Django 3.0.2 on 2020-03-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200328_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptable',
            name='image',
            field=models.ImageField(upload_to='group_pics'),
        ),
    ]
