# Generated by Django 3.0.4 on 2020-04-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifId', models.IntegerField()),
                ('itemId', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='item_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='return_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('ITEM', 'Item'), ('GROUP', 'Group')], default='PERSONAL', max_length=8),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='SharedItemsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('shared_user', models.TextField(max_length=30)),
                ('borrowed_user', models.TextField(max_length=30)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Notification')),
            ],
        ),
    ]
