# Generated by Django 3.0.4 on 2020-04-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20200402_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acceptance',
        ),
    ]
