# Generated by Django 3.0.5 on 2020-04-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_delete_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('ITEM', 'Item'), ('GROUP', 'Group'), ('FRIEND', 'Friend')], default='PERSONAL', max_length=8),
        ),
    ]
