# Generated by Django 3.0.2 on 2020-03-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20200309_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
