# Generated by Django 3.0.2 on 2020-03-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_auto_20200323_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='groupid',
            field=models.IntegerField(null=True),
        ),
    ]
