# Generated by Django 3.0.5 on 2020-04-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='borrowed_n',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='points',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='shared_n',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='total_rating',
            field=models.IntegerField(null=True),
        ),
    ]
