# Generated by Django 3.0.5 on 2020-04-03 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0003_auto_20200403_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='avg_rating',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='borrowed_n',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='shared_n',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
