# Generated by Django 3.0.2 on 2020-02-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200225_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='item',
            field=models.TextField(max_length=50),
        ),
    ]
