# Generated by Django 3.0.2 on 2020-02-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20200226_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='condition',
            field=models.CharField(choices=[('GD', 'good'), ('AVG', 'average'), ('BD', 'bad')], default='AVG', max_length=3),
        ),
    ]
