# Generated by Django 3.0.2 on 2020-02-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_itemlist_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
