# Generated by Django 3.0.4 on 2020-04-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_itemlist_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='ItemStatus',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT-AVAILABLE', 'Not-Available')], default='AVAILABLE', max_length=13),
        ),
        migrations.AddField(
            model_name='itemlist',
            name='image',
            field=models.ImageField(default='Items_pics/default.jpg', upload_to='Items_pics'),
        ),
    ]
