# Generated by Django 3.0.4 on 2020-04-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20200401_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='image',
            new_name='Image',
        ),
    ]
